FROM golang:1.25-alpine

RUN apk add --no-cache nodejs npm git
RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air"]
