FROM golang:1.25-alpine

RUN apk add --no-cache curl git unzip
RUN curl -fsSL https://bun.sh/install | sh
ENV PATH="/root/.bun/bin:${PATH}"
RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air"]
